version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Docker/web.docker
    restart: always
    ports:
      - "8000:80"
    volumes_from:
      - app
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: Docker/app.docker
    restart: always
    volumes:
      - ./:/var/www/SMS_Sender
    depends_on:
      - mysql
      - redis
    links:
      - mysql
    environment:
      DB_USER: sms_user
      DB_PASSWORD: sms_password
      DB_NAME: sms_sender
      DB_HOST: mysql

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sms_sender
      - MYSQL_USER=sms_user
      - MYSQL_PASSWORD=sms_password
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:3.0
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: sms_user
      DB_PASSWORD: sms_password
      DB_NAME: sms_sender
      DB_HOST: mysql