
version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/home/don/projects/SMS_Sender/SMS_Sender/
    ports:
      - "8080:80"
    links:
      - app

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql

  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/home/don/projects/SMS_Sender/SMS_Sender/